// Write the Figma plugin Figma actually runs: figma-plugin/dist/code.js and figma-plugin/dist/ui.html.
//
//   node build-plugin.mjs [--out <dir>] [--token <64 hex>]
//
// No dependencies and no bundler: the plugin is three sources pasted together in a fixed order.
//
//   dist/code.js  = the builder (tools/builder4.js BUILDER_SRC) as an ordinary async function, PXF_BUILD
//                 + the verifier (VERIFIER_SRC) the same way, PXF_VERIFY
//                 + figma-plugin/src/code.js, the host, inside its own function scope
//   dist/ui.html  = figma-plugin/src/ui.html with this run's key written in, or none
//
// The builder and the verifier used to travel inside every job payload as text and be compiled in
// Figma from that text. Now they are part of the plugin, compiled once when Figma loads it, and a
// payload is data only. That is also why this runs on every start of the runner (tools/session.mjs):
// a change to builder4.js reaches Figma the next time the plugin is opened, not through a repack.
//
// The key goes into ui.html because a web page cannot read a file on this disk, so a request that
// carries it can only have come from this plugin's window (tools/jobserver.mjs). dist/ is generated
// and must never be committed: it holds the key of the last run.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BUILDER_SRC, VERIFIER_SRC } from "./builder4.js";

const HERE = dirname(fileURLToPath(import.meta.url));
export const PLUGIN_DIR = join(HERE, "..", "figma-plugin");
export const DIST_DIR = join(PLUGIN_DIR, "dist");
const TOKEN_SLOT = '"__PXF_TOKEN__"';
const NL = String.fromCharCode(10);

// What may never appear in dist/, checked here so that a generated plugin that breaks the rule is
// never written, and again by tools/test-plugin.mjs over what was written. Coarse on purpose: a
// harmless identifier that happens to end in "Function(" fails it too, and is renamed.
export const FORBIDDEN = [
  [/\beval\s*\(/, "eval("],
  [/Function\s*\(/, "Function("],
  [/AsyncFunction/, "the async-function constructor"],
  [/getPrototypeOf\s*\(\s*async\b/, "the async-function constructor"],
  [/\bset(?:Timeout|Interval)\s*\(\s*["'`]/, "a timer given a string to compile"],
];
export function forbiddenIn(text) {
  const hits = [];
  for (const [re, what] of FORBIDDEN) if (re.test(text)) hits.push(what);
  return hits;
}

export function generatePlugin({ token = "" } = {}) {
  if (token && !/^[0-9a-f]{64}$/.test(token)) throw new Error("build-plugin: the token must be 64 lowercase hex characters");
  const host = readFileSync(join(PLUGIN_DIR, "src", "code.js"), "utf8");
  const uiSrc = readFileSync(join(PLUGIN_DIR, "src", "ui.html"), "utf8");

  // Names the plugin build in its own log and in every ping and probe report, so a report says which
  // builder produced it. A hash of the inputs, not a time: the same sources give the same build.
  const version = createHash("sha256").update(BUILDER_SRC).update(NL).update(VERIFIER_SRC).update(NL)
    .update(host).digest("hex").slice(0, 12);

  const code = [
    "// GENERATED by tools/build-plugin.mjs from tools/builder4.js and figma-plugin/src/code.js. Do not edit:",
    "// it is rewritten every time the runner starts. Edit the sources.",
    "var PXF_VERSION = " + JSON.stringify(version) + ";",
    "",
    "// ---- tools/builder4.js BUILDER_SRC ----",
    "async function PXF_BUILD(figma, PAY) {",
    "let RESULT = null;",
    BUILDER_SRC,
    "return RESULT;",
    "}",
    "",
    "// ---- tools/builder4.js VERIFIER_SRC ----",
    "async function PXF_VERIFY(figma, PAY, ROOT_NODE_ID) {",
    "let RESULT = null;",
    VERIFIER_SRC,
    "return RESULT;",
    "}",
    "",
    "// ---- figma-plugin/src/code.js ----",
    "(function () {",
    host,
    "})();",
    "",
  ].join(NL);

  const slots = uiSrc.split(TOKEN_SLOT).length - 1;
  if (slots !== 1) throw new Error("build-plugin: src/ui.html must hold exactly one " + TOKEN_SLOT + ", found " + slots);
  const ui = "<!-- GENERATED by tools/build-plugin.mjs from figma-plugin/src/ui.html. Do not edit, do not commit. -->" + NL +
    uiSrc.replace(TOKEN_SLOT, JSON.stringify(token));

  for (const [name, text] of [["dist/code.js", code], ["dist/ui.html", ui]]) {
    const hits = forbiddenIn(text);
    if (hits.length) throw new Error("build-plugin: " + name + " would contain " + hits.join(", ") + " — no code may be compiled from strings");
  }
  return { code, ui, version };
}

// Writes both files and returns what it wrote, so a caller that has to undo it (another runner already
// holds the port) can put the previous files back.
export function buildPlugin({ outDir = DIST_DIR, token = "" } = {}) {
  const g = generatePlugin({ token });
  mkdirSync(outDir, { recursive: true });
  const codePath = join(outDir, "code.js"), uiPath = join(outDir, "ui.html");
  writeFileSync(codePath, g.code, "utf8");
  writeFileSync(uiPath, g.ui, "utf8");
  return { codePath, uiPath, version: g.version, tokenWritten: !!token };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const flag = (n) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
  const out = flag("--out") ? resolve(flag("--out")) : DIST_DIR;
  const token = flag("--token") || "";
  const b = buildPlugin({ outDir: out, token });
  console.log("plugin build " + b.version + " -> " + out + (token ? " (with a key)" : " (no key: the window will ask for the runner's code)"));
}
